-- =============================================================================
-- Backfill — Payments retroactivos para cobranza histórica
-- =============================================================================
-- ⚠️  AMBOS INTENTOS FUERON REVERTIDOS. NO CORRER NINGUNO TAL CUAL.
--
-- Este archivo documenta dos intentos fallidos ejecutados el 2026-04-26
-- después de tightear /rutas para exigir Payment respaldando (PR #27 →
-- main). Pre-fix la cobranza vivía en PaymentSchedule.montoPagado sin
-- Payment, así que las semanas pasadas quedaron en 0%/1% al cambiar la
-- métrica.
--
-- Lección: la data histórica NO permite distinguir cobros reales de
-- "marcado-como-pagado" automáticamente. Cualquier intento que use
-- únicamente señales como `montoPagado > 0` o `audit log de apply`
-- termina inflando la métrica con basura. Para rescatar cobranza
-- histórica de forma confiable hay que cruzar contra extractos
-- bancarios / caja real con intervención humana, o aceptar que el
-- pasado se quede como está.
--
-- =============================================================================
-- v1 — REVERTIDO
-- =============================================================================
-- Filtro:  estado IN ('PAID','ADVANCE','PARTIAL') AND montoPagado > 0
--          AND no existe Payment.
-- Insertó: 2,588 Payments / $2,566,575 (dic-2025 → may-2026).
-- Fallo:   Capturó imports históricos (Tenancingo / San Mateo Atenco),
--          group applies viejos pre-fix, y marcados manuales sin
--          respaldo de caja. Resultado: métrica inflada con basura.
-- Rollback: DELETE FROM "Payment" WHERE notas LIKE 'Backfill: cobranza histórica%';
--
-- =============================================================================
-- v2 — REVERTIDO
-- =============================================================================
-- Filtro:  Cruz con AuditLog. Solo schedules con audit
--          DG_APPLY_PAYMENT (registroId = scheduleId) o
--          DG_APPLY_PAYMENT_GRUPO (groupId + numeroPago + pagadoAt
--          dentro de ±10 min del audit).
-- Insertó: 1,310 Payments / $1,186,350 (11-abr → 26-abr 2026).
-- Fallo:   Las audits DG_APPLY_PAYMENT* no distinguen "transferencia
--          recibida en banco" de "operación administrativa" (cerrar
--          loan, liquidar para renovación sin usar el flujo activate,
--          etc.). v2 backfill respaldó audits que en realidad eran
--          admin ops como si fueran cobros reales.
--          Caso testigo: Miguel Ángel salió con 2% cuando DG confirmó
--          que no había capturado nada — sus 3 schedules con Payment
--          venían de un group-apply audit del 23-abr que era admin op.
-- Rollback completo:
--          DELETE FROM "CashBreakdown" WHERE "paymentId" IN
--            (SELECT id FROM "Payment" WHERE notas LIKE 'Backfill v2%');
--          DELETE FROM "Ticket" WHERE "paymentId" IN
--            (SELECT id FROM "Payment" WHERE notas LIKE 'Backfill v2%');
--          UPDATE "ScoreEvent" SET "paymentId" = NULL WHERE "paymentId" IN
--            (SELECT id FROM "Payment" WHERE notas LIKE 'Backfill v2%');
--          DELETE FROM "Payment" WHERE notas LIKE 'Backfill v2%';
--
-- =============================================================================
-- Cleanup adicional (también revertido)
-- =============================================================================
-- Después del v2 backfill, intentamos limpiar quirúrgicamente schedules
-- de loans con renovación posterior cuyo pagadoAt estaba dentro de
-- ±2 días de la fecha del loan-hijo (renovación). Convertía a
-- FINANCIADO y borraba sus Payments. Tocó 27 schedules (Cristi 5,
-- Jaime 18, Luis Alberto 3). El cleanup se revirtió junto con el v2
-- backfill porque el problema de fondo era el v2.
--
-- Rollback del cleanup:
--          UPDATE "PaymentSchedule" ps SET estado = 'PAID'
--          FROM "Loan" l, "Loan" lnew
--          WHERE ps."loanId" = l.id AND lnew."loanOriginalId" = l.id
--            AND ps.estado = 'FINANCIADO'
--            AND ps."pagadoAt" BETWEEN lnew."fechaDesembolso" - interval '2 days'
--                                  AND lnew."fechaDesembolso" + interval '2 days';
--
-- =============================================================================
-- Estado final post-revertidos
-- =============================================================================
-- Cobranza histórica = solo Payments creados vía flujo normal
-- (`/cobros/capturar`, endpoints `apply` post-fix de PR #27, etc.).
-- Pasado pre-fix sale bajo. Going forward queda limpio: cualquier
-- captura crea Payment + actualiza CashRegister automáticamente.
--
-- =============================================================================
